isbn_error_menu="\n'MAIN MENU > MANAGE BOOKS > ISBN ERROR'\n1. Enter different ISBN.\n2. Previous Menu.\n"
user_id_error_menu="\n'MAIN MENU > MANAGE USERS > USER_ID ERROR'\n1. Enter different user_id.\n2. Previous Menu.\n"
manage_books="\n'MAIN MENU > MANAGE BOOKS'\n1. Add Book.\n2. Search Book by Title.\n3. Search Book by Author.\n4. Search Book by ISBN.\n5. List all books.\n6. Delete book. \n7. Update book.\n8. Previous Menu.\n"
manage_users="\n'MAIN MENU > MANAGE USERS'\n1. Add User.\n2. Search User by name.\n3. Search User by ID.\n4. List all users.\n5. Delete user.\n6. Update user.\n7. Previous Menu.\n"
main_menu="\n'MAIN MENU'\n1. Manage Books\n2. Manage Users\n3. Manage Checkins/Checkouts\n4. Exit\n"
check_menu="\n'MAIN MENU > MANAGE CHECKS'\n1. Checkin\n2. Checkout\n3. Previous Menu\n"